services:
    postgres:
        image: postgres:16-alpine
        restart: unless-stopped
        container_name: ${DATABASE_NAME}
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_PORT=${DATABASE_PORT}
            - POSTGRES_HOST=${DATABASE_HOST}
            - POSTGRES_DB=${DATABASE_NAME}
        ports:
            - "${DATABASE_PORT}:5432"
