FROM oven/bun:1.1.33-debian
LABEL maintainer="<NeatTeam />"

ENV APP_HOST="" APP_NAME=""
ENV API_PORT=50001 DOC_PORT=50002 DAPP_PORT=50003 BOT_PORT=50004 SITE_PORT=50005

ENV TELEGRAM_API_TOKEN="" TELEGRAM_SECRET_KEY=""

ENV JWT_ACCESS_KEY="" JWT_ACCESS_EXPIRES="15m" JWT_REFRESH_KEY="" JWT_REFRESH_EXPIRES="2d"

ENV ADMIN__JWT_ACCESS_KEY="" ADMIN__JWT_ACCESS_EXPIRES="2m" ADMIN__JWT_REFRESH_KEY="" ADMIN__JWT_REFRESH_EXPIRES="1d"

ENV DATABASE_USER="" DATABASE_PASSWORD="" DATABASE_HOST=localhost DATABASE_PORT=51000 DATABASE_NAME="" DATABASE_SCHEMA=public

ENV DATABASE_URL="postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME?schema=$DATABASE_SCHEMA"

ENV CACHE_NAME="" CACHE_USER="" CACHE_PASSWORD="" CACHE_PORT=51001


WORKDIR /Thodle
COPY ./prod .
COPY ./package.json .


RUN apt update && apt upgrade -y
RUN bun install
